member_checkin/urls.py
from django.urls import path

from . import views

app_name = 'member_checkin'
urlpatterns = [
    path('', views.MembersView.as_view(), name='members'),

    path('member', views.MembersView.as_view(), name='members'),
    path('member/create', views.MemberCreateView.as_view(), name='member_create'),
    path('member/<str:pk>/', views.MemberView.as_view(), name='member'),
    path('member/<str:pk>/update', views.MemberUpdateView.as_view(), name='member_update'),
    path('member/<str:pk>/delete', views.MemberDeleteView.as_view(), name='member_delete'),

    path('checkin', views.CheckInsView.as_view(), name='checkins'),
    path('checkin/create', views.CheckInCreateView.as_view(), name='checkin_create'),
    path('checkin/<int:pk>/', views.CheckInView.as_view(), name='checkin'),
    path('checkin/<int:pk>/delete/', views.CheckInDeleteView.as_view(), name='checkin_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('member_checkin/', include('member_checkin.urls')),
    path('admin/', admin.site.urls),
]

member_checkin/models.py
from django.db import models
from django.utils import timezone


class Member(models.Model):
    first_name = models.CharField(max_length=36, blank=True, null=True)
    last_name = models.CharField(max_length=36, blank=True, null=True)
    member_id = models.CharField(max_length=36, blank=True, null=True)
    card_id = models.CharField(max_length=36, blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.first_name + " " + self.last_name


class CheckIn(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.member.first_name + " " + self.member.last_name

member_checkin/views.py
from django.http import HttpResponse
from .models import CheckIn, Member
from django.views import generic
from django.utils import timezone
from django.shortcuts import get_object_or_404, render, reverse
from django.utils.timezone import localtime, now
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.core.exceptions import ValidationError
from django.db.models import Q


# Member Views CRUD

@method_decorator(csrf_exempt, name='dispatch')
class MemberCreateView(generic.CreateView):
    mode = Member
    fields = ['first_name', 'last_name', 'member_id', 'card_id']
    template_name = 'member_checkin/member_create.html'

    def get_queryset(self):
        return Member.objects.all()

    def get_success_url(self):
        return reverse('member_checkin:members')


class MembersView(generic.ListView):
    template_name = 'member_checkin/members.html'
    context_object_name = 'members_list'

    def get_queryset(self):
        filter_val = self.request.GET.get('search')
        if filter_val:
            print("f" + filter_val)
            new_context = Member.objects.filter(
                Q(last_name__contains=filter_val) | Q(first_name__contains=filter_val) | Q(
                    member_id__contains=filter_val)).order_by("last_name", "first_name", "member_id")
        else:
            new_context = Member.objects.all().order_by("last_name", "first_name", "member_id")
        return new_context


class MemberView(generic.DetailView):
    model = Member
    template_name = 'member_checkin/member.html'


class MemberUpdateView(generic.UpdateView):
    mode = Member
    fields = ['first_name', 'last_name', 'member_id', "card_id"]
    template_name = 'member_checkin/member_update.html'

    def get_queryset(self):
        return Member.objects.all()

    def get_success_url(self):
        return reverse('member_checkin:members')


class MemberDeleteView(generic.DeleteView):
    mode = Member
    template_name = 'member_checkin/member_delete.html'
    success_url = reverse_lazy('member_checkin:members')

    def get_queryset(self):
        return Member.objects.all()


@method_decorator(csrf_exempt, name='dispatch')
class CheckInCreateView(generic.CreateView):
    mode = CheckIn
    fields = ['member']
    template_name = 'member_checkin/checkin_create.html'

    def get_queryset(self):
        return CheckIn.objects.all()

    def get_success_url(self):
        return reverse('member_checkin:checkins')


class CheckInsView(generic.ListView):
    template_name = 'member_checkin/checkins.html'
    context_object_name = 'checkins_list'

    def get_queryset(self):
        filter_val = self.request.GET.get('search')
        if filter_val:
            print("f" + filter_val)
            new_context = CheckIn.objects.filter(
                Q(member__last_name__contains=filter_val) | Q(member__first_name__contains=filter_val)).order_by(
                "created")
        else:
            new_context = CheckIn.objects.all().order_by("created")
        return new_context


class CheckInView(generic.DetailView):
    model = CheckIn
    template_name = 'member_checkin/checkin.html'


class CheckInDeleteView(generic.DeleteView):
    model = CheckIn
    template_name = 'member_checkin/checkin_delete.html'
    success_url = reverse_lazy('member_checkin:checkins')

member_checkin/templates/member_checkin/checkin.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Check In</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<script>M.AutoInit();</script>

<table>
    <tr>
        <td><p>Member:</p></td>
        <td>
            <a href="{% url 'member_checkin:member' checkin.member.id %}">{{ checkin.member }}</a>
        </td>
    </tr>
    <tr>
        <td><p>Created:</p>
        </th>
        <td><p>{{ checkin.created|date:'Y-m-d H:i:s' }}</p>
        </th>
    </tr>
</table>
<a href="{% url 'member_checkin:checkin_delete' checkin.id %}"
   class="btn-floating btn-large waves-effect waves-light red"><i
        class="material-icons">delete</i></a>

member_checkin/templates/member_checkin/checkin_create.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Check In Create</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<script>M.AutoInit();</script>

<form method="post">
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
<script>M.AutoInit();</script>

member_checkin/templates/member_checkin/checkin_delete.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Check In Delete</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<script>M.AutoInit();</script>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
     <p>Are you sure you want to delete check in "{{ object }}"?</p>
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
  </button>
</form>

member_checkin/templates/member_checkin/checkins.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a class="brand-logo center">Check Ins</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<nav>
    <div class="nav-wrapper">
        <form>
            <div class="input-field">
                <input id="search" name="search" type="search">
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
            </div>
        </form>
    </div>
</nav>



{% if checkins_list %}
    <div class="collection">
        {% for checkin in checkins_list %}
            <a href="{% url 'member_checkin:checkin' checkin.id %}" class="collection-item">
                <span class="badge">{{ checkin.member }}</span>{{ checkin.created|date:'Y-m-d H:i:s' }}
            </a>
        {% endfor %}
    </div>
{% else %}
    <p>No check ins are available.</p>
{% endif %}
<a href="{% url 'member_checkin:checkin_create' %}" class="btn-floating btn-large waves-effect waves-light red"><i
        class="material-icons">playlist_add</i></a>

<script>M.AutoInit();</script>

member_checkin/templates/member_checkin/member.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Member</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<script>M.AutoInit();</script>

<table>
    <tr>
        <td><p>Last Name:</p></td>
        <td><p>{{ member.last_name }}</p></td>
    </tr>
    <tr>
        <td><p>First Name:</p></td>
        <td><p>{{ member.first_name }}</p></td>
    </tr>
    <tr>
        <td><p>Member Id:</p></td>
        <td><p>{{ member.member_id }}</p></td>
    </tr>
    <tr>
        <td><p>Card Id:</p></td>
        <td><p>{{ member.card_id }}</p></td>
    </tr>
    <tr>
        <td><p>Created:</p></td>
        <td><p>{{ member.created|date:'Y-m-d H:i:s' }}</p></td>
    </tr>
    <th><a href="{% url 'member_checkin:member_update' member.id %}"
           class="btn-floating btn-large waves-effect waves-light red"><i
            class="material-icons">edit</i></a>
    </th>
    <th><a href="{% url 'member_checkin:member_delete' member.id %}"
           class="btn-floating btn-large waves-effect waves-light red"><i
            class="material-icons">delete</i></a></th>
    </tr>
</table>

member_checkin/templates/member_checkin/member_create.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Member</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<script>M.AutoInit();</script>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right"></i>
  </button>
</form>

member_checkin/templates/member_checkin/member_delete.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Member</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<script>M.AutoInit();</script>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
     <p>Are you sure you want to delete member "{{ object }}"?</p>
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right"></i>
  </button>
</form>

member_checkin/templates/member_checkin/member_update.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Member</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<script>M.AutoInit();</script>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right"></i>
  </button>
</form>

member_checkin/templates/member_checkin/members.html
{% load static %}
<link rel="stylesheet" href="{% static "materialize/css/materialize.css" %}">
<script type="text/javascript" src="{% static "materialize/js/materialize.js" %}"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<nav>
    <div class="nav-wrapper">
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
        <a href="#" class="brand-logo center">Members</a>
    </div>
</nav>


<ul id="slide-out" class="sidenav sidenav-fixed">
    <li>
        <div class="user-view">
            <div class="background">
            </div>
            <a><img class="circle"></a>
            <a><span class="white-text name">John Doe</span></a>
            <a><span class="white-text email">jdandturk@gmail.com</span></a>
        </div>
    </li>
    <li><a href="{% url 'member_checkin:members' %}"><i class="material-icons">person</i>Members</a></li>
    <li><a href="{% url 'member_checkin:checkins' %}"><i class="material-icons">insert_chart</i>Check Ins</a></li>
</ul>

<nav>
    <div class="nav-wrapper">
        <form>
            <div class="input-field">
                <input id="search" name="search" type="search">
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
            </div>
        </form>
    </div>
</nav>

<script>M.AutoInit();</script>

{% if members_list %}
    <ul class="collection">
        {% for member in members_list %}
            <li class="collection-item avatar">
                <a href="{% url 'member_checkin:member' member.id %}">
                    <i class="material-icons circle">person</i>
                    <span class="title">{{ member.first_name }} {{ member.last_name }}</span>
                    <p>{{ member.member_id }}</p>
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No members are available.</p>
{% endif %}
<a href="{% url 'member_checkin:member_create' %}" class="btn-floating btn-large waves-effect waves-light red"><i
        class="material-icons">person_add</i></a>